name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels:
  - bug
assignees: []
body:
  - type: dropdown
    id: play_type
    attributes:
      label: Where did you find this bug?
      description: Choose where this issue happened.
      options:
        - Engine (inside Unreal Editor)
        - Build (packaged game)
        - Both
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: The player gets stuck after ending a turn while standing on a relic tile.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Tell us exactly how to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true
