;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Buff.DamageUp",DevComment="")
+GameplayTagList=(Tag="Buff.HealLink",DevComment="")
+GameplayTagList=(Tag="Buff.MoveUp",DevComment="")
+GameplayTagList=(Tag="Buff.Protection",DevComment="")
+GameplayTagList=(Tag="Buff.Protection.SetByCaller",DevComment="")
+GameplayTagList=(Tag="Buff.Regen",DevComment="")
+GameplayTagList=(Tag="Buff.Ward",DevComment="")
+GameplayTagList=(Tag="Buff.Ward.SetByCaller",DevComment="")
+GameplayTagList=(Tag="Buff.WardLink",DevComment="")
+GameplayTagList=(Tag="Damage.SetByCaller",DevComment="")
+GameplayTagList=(Tag="Debuff.Bleed",DevComment="")
+GameplayTagList=(Tag="Debuff.Burn",DevComment="")
+GameplayTagList=(Tag="Debuff.MovementDown",DevComment="")
+GameplayTagList=(Tag="Debuff.Poison",DevComment="")
+GameplayTagList=(Tag="Debuff.Stun",DevComment="")
+GameplayTagList=(Tag="Debuff.Taunted",DevComment="")
+GameplayTagList=(Tag="Debuff.Vulnerable",DevComment="")
+GameplayTagList=(Tag="Debuff.Weakness",DevComment="")
+GameplayTagList=(Tag="Effect.EndOfCombat",DevComment="")
+GameplayTagList=(Tag="Effect.EndOfTurn",DevComment="If present on an effect, one stack is removed at the end of the turn")
+GameplayTagList=(Tag="Effect.EndOfTurn.RemoveAllStacks",DevComment="If present on an end-of-turn effect, all stacks are removed instead of one")
+GameplayTagList=(Tag="Effect.StartOfTurn",DevComment="If present on an effect, one stack is removed at the start of the turn")
+GameplayTagList=(Tag="Effect.StartOfTurn.RemoveAllStacks",DevComment="If present on a start-of-turn effect, all stacks are removed instead of one")
+GameplayTagList=(Tag="Heal.SetByCaller",DevComment="")
+GameplayTagList=(Tag="Status.BuffNextTurn",DevComment="")
+GameplayTagList=(Tag="Status.Burn",DevComment="")
+GameplayTagList=(Tag="Status.DamageDown",DevComment="")
+GameplayTagList=(Tag="Status.DamageUp",DevComment="")
+GameplayTagList=(Tag="Status.Giant",DevComment="")
+GameplayTagList=(Tag="Status.Poison",DevComment="")
+GameplayTagList=(Tag="Status.Protection.SetByCaller",DevComment="")
+GameplayTagList=(Tag="Status.Rage",DevComment="")
+GameplayTagList=(Tag="Status.Regen",DevComment="")
+GameplayTagList=(Tag="Status.Taunted",DevComment="")
+GameplayTagList=(Tag="Swirly.Cleanse",DevComment="")
+GameplayTagList=(Tag="Ward.SetByCaller",DevComment="")

